### ISSUE TITLE
Update Dokka

### ISSUE THREAD

**Issue by InsanusMokrassar** [InsanusMokrassar/TelegramBotAPI#152]
Update `Dokka` dependency and its configurations

**Comment by lingarajsankaravelu** [comment]
I like to take this up

**Comment by Megamiun** [comment]
Can you assign it to me?

**Comment by Megamiun** [comment]
Solved, although I change a little the `includeSourcesInDokka` because I got confused on how to use Closures inside Groovy

**Comment by InsanusMokrassar** [comment]
It works on https://tgbotapi.inmo.dev/docs/ :) thank you for help. I am closing this issue as solved
