### ISSUE TITLE
Support for ability to manually specify text entities instead of specifying the parse_mode

### ISSUE THREAD

**Issue by madhead** [InsanusMokrassar/TelegramBotAPI#189]
Added the ability to manually specify text entities instead of specifying the `parse_mode` in the classes [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaAudio](https://core.telegram.org/bots/api#inputmediaaudio), [InputMediaDocument](https://core.telegram.org/bots/api#inputmediadocument), [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto), [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif), [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo), [InlineQueryResultAudio](https://core.telegram.org/bots/api#inlinequeryresultaudio), [InlineQueryResultVoice](https://core.telegram.org/bots/api#inlinequeryresultvoice), [InlineQueryResultDocument](https://core.telegram.org/bots/api#inlinequeryresultdocument), [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto), [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif), [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif), [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo), [InlineQueryResultCachedAudio](https://core.telegram.org/bots/api#inlinequeryresultcachedaudio), [InlineQueryResultCachedVoice](https://core.telegram.org/bots/api#inlinequeryresultcachedvoice), [InlineQueryResultCachedDocument](https://core.telegram.org/bots/api#inlinequeryresultcacheddocument), [InputTextMessageContent](https://core.telegram.org/bots/api#inputtextmessagecontent) and the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [editMessageText](https://core.telegram.org/bots/api#editmessagetext), [editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption).

**Comment by InsanusMokrassar** [comment]
## Types

* [ ] [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto)
* [ ] [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo)
* [ ] [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation)
* [ ] [InputMediaAudio](https://core.telegram.org/bots/api#inputmediaaudio)
* [ ] [InputMediaDocument](https://core.telegram.org/bots/api#inputmediadocument)
* [ ] [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto)
* [ ] [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif)
* [ ] [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif)
* [ ] [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo)
* [ ] [InlineQueryResultAudio](https://core.telegram.org/bots/api#inlinequeryresultaudio)
* [ ] [InlineQueryResultVoice](https://core.telegram.org/bots/api#inlinequeryresultvoice)
* [ ] [InlineQueryResultDocument](https://core.telegram.org/bots/api#inlinequeryresultdocument)
* [ ] [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto)
* [ ] [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif)
* [ ] [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif)
* [ ] [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo)
* [ ] [InlineQueryResultCachedAudio](https://core.telegram.org/bots/api#inlinequeryresultcachedaudio)
* [ ] [InlineQueryResultCachedVoice](https://core.telegram.org/bots/api#inlinequeryresultcachedvoice)
* [ ] [InlineQueryResultCachedDocument](https://core.telegram.org/bots/api#inlinequeryresultcacheddocument)
* [ ] [InputTextMessageContent](https://core.telegram.org/bots/api#inputtextmessagecontent)

## Methods

* [ ] [sendMessage](https://core.telegram.org/bots/api#sendmessage)
* [ ] [sendPhoto](https://core.telegram.org/bots/api#sendphoto)
* [ ] [sendVideo](https://core.telegram.org/bots/api#sendvideo)
* [ ] [sendAnimation](https://core.telegram.org/bots/api#sendanimation)
* [ ] [sendAudio](https://core.telegram.org/bots/api#sendaudio)
* [ ] [sendDocument](https://core.telegram.org/bots/api#senddocument)
* [ ] [sendVoice](https://core.telegram.org/bots/api#sendvoice)
* [ ] [sendPoll](https://core.telegram.org/bots/api#sendpoll)
* [ ] [editMessageText](https://core.telegram.org/bots/api#editmessagetext)
* [ ] [editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption)
