### ISSUE TITLE
Support for allow_sending_without_reply flag

### ISSUE THREAD

**Issue by madhead** [InsanusMokrassar/TelegramBotAPI#191]
Added the field `allow_sending_without_reply` to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendInvoice](https://core.telegram.org/bots/api#sendinvoice), [sendGame](https://core.telegram.org/bots/api#sendgame), [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) to allow sending messages not a as reply if the replied-to message has already been deleted.

**Comment by InsanusMokrassar** [comment]
* [ ] [sendMessage](https://core.telegram.org/bots/api#sendmessage)
* [ ] [sendPhoto](https://core.telegram.org/bots/api#sendphoto)
* [ ] [sendVideo](https://core.telegram.org/bots/api#sendvideo)
* [ ] [sendAnimation](https://core.telegram.org/bots/api#sendanimation)
* [ ] [sendAudio](https://core.telegram.org/bots/api#sendaudio)
* [ ] [sendDocument](https://core.telegram.org/bots/api#senddocument)
* [ ] [sendSticker](https://core.telegram.org/bots/api#sendsticker)
* [ ] [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote)
* [ ] [sendVoice](https://core.telegram.org/bots/api#sendvoice)
* [ ] [sendLocation](https://core.telegram.org/bots/api#sendlocation)
* [ ] [sendVenue](https://core.telegram.org/bots/api#sendvenue)
* [ ] [sendContact](https://core.telegram.org/bots/api#sendcontact)
* [ ] [sendPoll](https://core.telegram.org/bots/api#sendpoll)
* [ ] [sendDice](https://core.telegram.org/bots/api#senddice)
* [ ] [sendInvoice](https://core.telegram.org/bots/api#sendinvoice)
* [ ] [sendGame](https://core.telegram.org/bots/api#sendgame)
* [ ] [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup)
