### ISSUE TITLE
Check if cachedTimeField is incorrect

### ISSUE THREAD

**Issue by InsanusMokrassar** [InsanusMokrassar/TelegramBotAPI#272]
https://core.telegram.org/bots/api#answerinlinequery

**Comment by y9san9** [comment]
Sources:

https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/requests/answers/AnswerInlineQuery.kt#L20

https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/Common.kt#L126

**Comment by InsanusMokrassar** [comment]
> Sources:
> 
> https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/requests/answers/AnswerInlineQuery.kt#L20
> 
> https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/Common.kt#L126

Thank you
