### ISSUE TITLE
Add opportunity to setup default parseMode

### ISSUE THREAD

**Issue by InsanusMokrassar** [InsanusMokrassar/TelegramBotAPI#291]
It would be useful to add some global variable which will be used as default parse mode

**Comment by y9san9** [comment]
For me better solution is to add `parseMode` parameter inside `sendMessage` method with entities (but it may take long time to do because of huge amount of methods)

**Comment by InsanusMokrassar** [comment]
Inside of methods with entities list there are not parameters for parseMode due to the fact that this parameter is redundant for list of entities and will not be used by telegram system

**Comment by y9san9** [comment]
So, I see, then I dunno what I can do if I need to send entities in any format. 
Maybe if parseMode != null, you can manually convert it to string and it with the mode?

**Comment by InsanusMokrassar** [comment]
What for?

**Comment by InsanusMokrassar** [comment]
If you need, you always can convert `List<TextSource>` to string in required format with [one of the methods in resending tools](https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/formatting/ResendingTextFormatting.kt)

**Comment by y9san9** [comment]
I am, but that is not convenient way :disappointed: 
![image](https://user-images.githubusercontent.com/46930374/107174561-98f6d680-69db-11eb-9376-072064fc54c6.png)

**Comment by InsanusMokrassar** [comment]
You may use list of text sources OR text + parse mode. So, currently I do not see any reasons to convert your text sources to text

**Comment by y9san9** [comment]
Inline mentions don't work with entities

**Comment by y9san9** [comment]
I think something like this will be enough
![image](https://user-images.githubusercontent.com/46930374/107175351-a614c500-69dd-11eb-820b-a99f422c0072.png)
