### ISSUE TITLE
Listen for all IPs even without SSL config

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#50]
I host my bot on heroku, which itself controls everything that is necessary for https. So I don't need and I simply can't provide SSL configuration. But, I should listen for 0.0.0.0, not localhost.

**Comment by Djaler** [comment]
I found a workaround for now, but this is ugly https://github.com/Djaler/evil-bot/blob/19194c5ec04e3ce562377999036a54af936e468e/src/main/kotlin/com/github/djaler/evilbot/components/BotInitializer.kt#L35

**Comment by InsanusMokrassar** [comment]
For now, it is required to pass only information about url (`0.0.0.0`, `localhost` or something else), port, engine factory (like CIO (I am not recommend it)) and update receiver

**Comment by InsanusMokrassar** [comment]
Of course, you can use method with signature `setWebhook(String, Int, UpdatesFilter, ApplicationEngineFactory,...)`, but anyway it is not required to use certificate

**Comment by Djaler** [comment]
Url is an application address, to which requests will be sent after installing the webhook. I am talking about `host`, which you override here https://github.com/InsanusMokrassar/TelegramBotAPI/blob/0ef4341bafb111eacb7cf147b51605848bb88ed8/src/jvmMain/kotlin/com/github/insanusmokrassar/TelegramBotAPI/utils/extensions/Webhooks.kt#L95

**Comment by Djaler** [comment]
host is "0.0.0.0" by default both in ssl connector and simple connector. I don't thin you should override it.

**Comment by InsanusMokrassar** [comment]
Understand and fix in https://github.com/InsanusMokrassar/TelegramBotAPI/commit/43b08e93196e29445ffc1327ad1ca8642d3c75f3

**Comment by InsanusMokrassar** [comment]
So, if it is what you meant, I will  close issue and create new version `0.20.4`

**Comment by Djaler** [comment]
Yeah, looks like this is what I need. Thanks!

**Comment by InsanusMokrassar** [comment]
Glad to help!

Close due to there is fix in https://github.com/InsanusMokrassar/TelegramBotAPI/commit/43b08e93196e29445ffc1327ad1ca8642d3c75f3

**Comment by InsanusMokrassar** [comment]
@Djaler https://bintray.com/insanusmokrassar/StandardRepository/TelegramBotAPI/0.20.4

**Comment by Djaler** [comment]
Hmm. It works only if I specify both:
```
jcenter()
maven("https://dl.bintray.com/insanusmokrassar/StandardRepository")
```
and use artifact name `TelegramBotAPI-jvm` instead of `TelegramBotAPI`:
```
implementation("com.github.insanusmokrassar:TelegramBotAPI-jvm:0.20.4")
```

**Comment by Djaler** [comment]
Looks like this is because of multiplatform features of your library, because there also a `TelegramBotAPI-js`

**Comment by InsanusMokrassar** [comment]
https://blog.gradle.org/gradle-metadata-1.0

It is one of the gradle features. You can just update your gradle wrapper to 6.0 version or higher

**Comment by Djaler** [comment]
I already have 6.0.1

**Comment by Djaler** [comment]
Also, `TelegramBotAPI-jvm` is available only in your own repo (`https://dl.bintray.com/insanusmokrassar/StandardRepository`), not in main jcenter: https://jcenter.bintray.com/com/github/insanusmokrassar/

**Comment by InsanusMokrassar** [comment]
So, in this case it must be available using common notation TelegramBotAPI. If it is not, we will create new issue

**Comment by InsanusMokrassar** [comment]
I know about issue with jcenter, but for now I do not know how to solve it
