### ISSUE TITLE
Support for strikethrough message entity

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#53]
New bot API version was released yesterday: https://core.telegram.org/bots/api#december-31-2019

**Comment by InsanusMokrassar** [comment]
Hi, thanks for information. I will implement it as soon as possible

**Comment by InsanusMokrassar** [comment]
I have created new pull request: #54 . So, as I already said, I will implement new functionality as soon as possible

**Comment by InsanusMokrassar** [comment]
Fix explanation [here](https://github.com/InsanusMokrassar/TelegramBotAPI/issues/55#issuecomment-570275341)

**Comment by InsanusMokrassar** [comment]
@Djaler version 0.21.0 is available for using. More info you can get on [bintray [age](https://bintray.com/insanusmokrassar/StandardRepository/TelegramBotAPI/0.21.0) and in [CHANGELOG file](https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/CHANGELOG.md#0210-telegrambotapi-45)

**Comment by Djaler** [comment]
Awesome, thanks!

**Comment by InsanusMokrassar** [comment]
Welcome:)
