### ISSUE TITLE
Access from the jcenter

### ISSUE THREAD

**Issue by InsanusMokrassar** [InsanusMokrassar/TelegramBotAPI#56]
Currently it is impossible to use library without direct adding of repository (https://dl.bintray.com/insanusmokrassar/StandardRepository/) into repositories list

**Comment by InsanusMokrassar** [comment]
I have found the issue reason. Previously project was jvm-only and when I have to requested access to publishing into jcenter it was approved only for one required on that moment package: `com.github.insanusmokrassar.TelegramBotAPI`. For now I have written into support team for extending of publishing artifacts packages for the project https://bintray.com/insanusmokrassar/StandardRepository/TelegramBotAPI

**Comment by InsanusMokrassar** [comment]
@Djaler (mention cause of you have said about this issue):

Currently this library available directly from `jcenter` and with `TelegramBotAPI` name of dependency

**Comment by Djaler** [comment]
Thanks!

**Comment by Djaler** [comment]
Hmm, didn't work for me. Should it work with 0.21.0?

**Comment by Djaler** [comment]
There are no main jar in jcenter - https://jcenter.bintray.com/com/github/insanusmokrassar/TelegramBotAPI/0.21.0
And in maven central too - https://repo1.maven.org/maven2/com/github/insanusmokrassar/TelegramBotAPI/0.21.0/

**Comment by InsanusMokrassar** [comment]
It is look like for local maven it was built correctly, but for gradle and maven central is not-.- let me a few minutes

**Comment by InsanusMokrassar** [comment]
Unfortunatelly, it will take more time

**Comment by InsanusMokrassar** [comment]
@Djaler can you, please, try again to use `TelegramBotAPI` with `jcenter()`? I have checked on my environment, but it will be better, if you will check it too

**Comment by Djaler** [comment]
Still doesn't work

**Comment by InsanusMokrassar** [comment]
Can you send gradle build file which you are using to check?

**Comment by Djaler** [comment]
https://github.com/Djaler/evil-bot/blob/master/build.gradle.kts this

**Comment by InsanusMokrassar** [comment]
So, what have you changed? Repository and dependency?

**Comment by Djaler** [comment]
Yeah, I tried to remove `maven("https://dl.bintray.com/insanusmokrassar/StandardRepository")` and drop `-jvm` from dependency name

**Comment by InsanusMokrassar** [comment]
Ok, I will try this

**Comment by InsanusMokrassar** [comment]
I have fixed. From you will be better to do several additional actions:

* Move `jcenter` as primary source:

```groovy
repositories {
    jcenter()
    mavenCentral()
}
```

* And remove cache (on linux it will be `rm -rf ~/.m2/repository/com/github/insanusmokrassar/* ~/.gradle/caches/modules-2/files-2.1/com.github.insanusmokrassar`)

@Djaler please, let me know about results

**Comment by Djaler** [comment]
It works, thanks! Also, there are feature to use repository only for specific dependencies - https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_a_repository_filter, so I can make something like:
```
repositories {
    jcenter {
        content {
            includeGroup("com.github.insanusmokrassar")
        }
    }
    mavenCentral()
}
```

**Comment by InsanusMokrassar** [comment]
I think, it is up to you:) thank you
