### ISSUE TITLE
Not implemented cashtag parsing

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#61]
I got `kotlin.NotImplementedError: An operation is not implemented` error when received message with cashtag entity. Looks like this is the problem: https://github.com/InsanusMokrassar/TelegramBotAPI/blob/031c61a872f966a4bba2242b287282d332e6333b/src/commonMain/kotlin/com/github/insanusmokrassar/TelegramBotAPI/types/MessageEntity/RawMessageEntity.kt#L26

**Comment by Djaler** [comment]
And, as I said earlier, you should parse updates independently. Updates receiving shouldn't stop because of one failed update parsing

**Comment by InsanusMokrassar** [comment]
At least, I have solved problem with cashtag ([here](https://github.com/InsanusMokrassar/TelegramBotAPI/pull/62/commits/4182d66f6e6e36a708a2e824f74267c53fe8aa90))

**Comment by InsanusMokrassar** [comment]
In the same PR (#62 ) I have solved problem with unsupported functionality, so, I hope the same issue will not be repeated
