### ISSUE TITLE
Down vote on this library

### ISSUE THREAD

**Issue by nort3x** [InsanusMokrassar/TelegramBotAPI#703]
i spent couple of hours on this library,

abusing extension functions made this library impenetrable for newcomers
no actual repeatable pattern between components

is making this harder than it should be, at least for me and what i expect this to be

this is not criticism, author spend astonishing time on developing this
but it's too complex and crowded for what it is offering

**Comment by InsanusMokrassar** [comment]
Hello :) which components you are talking about? I tried hard to make api extensions to be as much useful as possible, but in case you have some suggestions about how to improve it - you are welcome

**Comment by nort3x** [comment]
I'm not an expert when it comes to writing clean code and I don't claim anything,
but here are some anti-patterns listed by other peoples:
https://github.com/ruXlab/absurd-kotlin


suppose i want to simply reply something in `onCommand` my IDE hangs for couple of seconds then it shows me a HUGE list of overloaded extension functions where with the same name and lot's of combination of parameters, i smell an oder on this

what is the point of extension functions when you can encapsulate code in your project?

maybe just maybe `extend by delegate` could be used to refactor this into separate interfaces or at least more direct imperative style like

```kotlin
command.matches{ it.content.startsWith("post_")}.process{ cmd ->

   val reply = cmd.makeReply() // makeMediaReply, makeDiceReply
   reply.inlineKeys = keys
   reply.text = regular("great!")
   
   val reply2 = cmd.chat.getMessageBeforeThisByOffset(3).awaitOrNull()?.makeReply()?.applly{//...}?.complete () //suspend

   reply.queue() //job
}

```

good naming conventions and being accessible in expected locations reduce need for documentation, after all we are writing code for humans not the compiler

- best regards

**Comment by InsanusMokrassar** [comment]
Are you sure that the sample you have sent is simpler than that:

```kotlin
reply(
    commandMessage,
    text,
    replyMarkup
)
```

?

**Comment by InsanusMokrassar** [comment]
In most cases when there are a lot of different extensions with the same name they will have changed main parameter (like which content to use)

**Comment by nort3x** [comment]
> Are you sure that the sample you have sent is simpler than that:
> 
> ```kotlin
> reply(
>     commandMessage,
>     text,
>     replyMarkup
> )
> ```
> 
> ?

at the end it's all about personal preferences,
but i want to emphasis on some points for whom might read this issue later,

when we use extension functions? 
* when we can't edit  already existing code (not the case here)

what it compiles to be?
* a static function with the receiver as it's first parameter

so why we need them?
* it's sugar to avoid remembering all of those static methods, with the help of receiver so extension methods semantically should have a strong correlation with their receiver

here to `reply` a `message`  which readily seems to relates to `message` is an extension on `TelegramBot` with lots of overloads which probably are scattered around the codebase, if this is not an anti pattern, i don't know what else is.

if i want to know what can i do with `message` type what i normally do is search for what methods are defined for this type and probably not else where ( which this type is taken as input) after all this is all extensions brought to the table for the price of slow builds and complex indexes.


https://user-images.githubusercontent.com/26030553/210086897-72501edd-dd56-42cb-9b66-5148a127b413.mp4


- best regards

**Comment by InsanusMokrassar** [comment]
You always can try something like `sendText`/`sendPhoto`/`etc.`. All the API extensions have been designed as extensions for one reason - whrn you want to decrease size of binary/count of methods (android case, but it is not actual for the latest versions). So, it is supposed that in case you wish to send text, you will type `bot.sendText(...)` or `bot.send(chatId, "text")` and that is easy to read (you always may understand, what was meant) and predict what will be called :)

Anyway, I will be glad to any suggestions. I am trying hard to make this lib better, so, I want to see as much ways, as possible, and correctly choose the best solutions :)

**Comment by InsanusMokrassar** [comment]
Thank you for this issue. I think I got your point and will think about how may I fix the problems you highlighted here.

Happy new year :tada:
