### ISSUE TITLE
FSM behaviour with multiple users

### ISSUE THREAD

**Issue by denchic45** [InsanusMokrassar/TelegramBotAPI#718]
I'm new to Telegram bot API, maybe I'm missing something. I made a test case in which, when entering the /start command, the bot prompts the user to enter his name. But the trouble is that when the conditional user A enters the / start command, the bot expects a message with a name from any other user, that is, the state itself appears to be general, and not a specific user. Here is an example behavior:
```kotlin
suspend fun DefaultBehaviourContextWithFSM<BotState>.buildBehaviour() {
    strictlyOn<YourNameState> { state ->
        val message = waitTextMessage().first()
        send(state.context, "Hello, ${message.content.text}")
        null
    }
    command("start") { message ->
        sendTextMessage(message.chat, "Type your name")
        startChain(YourNameState(message.chat))
    }
}

data class YourNameState(override val context: Chat) : BotState
```
This can be fixed by checking the chat from which the message was sent, then the bot will wait for a message only from the right user
```kotlin
suspend fun DefaultBehaviourContextWithFSM<BotState>.buildBehaviour() {
    strictlyOn<YourNameState> { state ->
        val message = waitTextMessage().filter { it.chat == state.context }.first()
        send(state.context, "Hello, ${message.content.text}")
        null
    }
    command("start") { message ->
        sendTextMessage(message.chat, "Type your name")
        startChain(YourNameState(message.chat))
    }
}
```
Is this behavior correct? It turns out that in order for the state to be individual for one or several users, do you need to filter the chat in messages?

**Comment by InsanusMokrassar** [comment]
Hello and thank you for your issue:)

Yes, it is expected behaviour due to no warranties that you want to get data from this chat :)
