### ISSUE TITLE
Error in startGettingOfUpdates

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#77]
I always get that exception
`java.net.ConnectException: Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443`
here: https://github.com/InsanusMokrassar/TelegramBotAPI/blob/c22c1bb1447b093dad4a12f3e690ce24797ebdfd/TelegramBotAPI-extensions-api/src/commonMain/kotlin/com/github/insanusmokrassar/TelegramBotAPI/extensions/api/updates/UpdatesPolling.kt#L61

**Comment by Djaler** [comment]
Looks like this happen when I specify 1 second timeout. With default (30 seconds) it works good. Strange

**Comment by InsanusMokrassar** [comment]
It can be related to the connection time. If you are using some proxy or VPN the time required for the establishing of connection is longer than just direct connect. So, you can try to reproduce it on some VPS or just without VPN or proxy

**Comment by Djaler** [comment]
I tries on local computer without any VPN or proxy. There are no problems after set default timeout, so I'll close this
